In [ ]:

from sklearn.datasets import fetch_openml
import numpy as np

# Cargar el conjunto de datos Kuzushiji-MNIST y convertir las etiquetas a números
mnist = fetch_openml('poker-hand', version=1)
mnist.target = mnist.target.astype(np.int64)

from sklearn.model_selection import train_test_split

# Dividir los datos en conjuntos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(
    mnist["data"], mnist["target"], random_state=42)

from sklearn.cluster import KMeans
k = 80  # Número de clústeres


kmeans = KMeans(n_clusters=k, random_state=42)#aqui

X_digits_dist = kmeans.fit_transform(X_train)


idxs = np.argmin(X_digits_dist, axis=0)


X_representative_digits = X_train.values[idxs]




/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(
/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


In [ ]:
# Mostrar las manos más representativas de cada cluster
for i in range(len(X_representative_digits)):
    print(f"Cluster {i+1}:")
    print(X_representative_digits[i])
    print("--------------------")



Cluster 1:
[ 2.  4.  3.  2.  2.  3.  3.  9.  3. 10.]
--------------------
Cluster 2:
[ 2. 11.  3. 12.  3. 10.  2.  3.  3.  3.]
--------------------
Cluster 3:
[ 2.  3.  3.  8.  2. 11.  3.  6.  2.  7.]
--------------------
Cluster 4:
[ 2. 11.  2.  7.  3. 11.  3.  8.  2.  3.]
--------------------
Cluster 5:
[ 3.  8.  3.  7.  2.  3.  3.  6.  2. 12.]
--------------------
Cluster 6:
[2. 3. 3. 7. 3. 4. 3. 6. 3. 8.]
--------------------
Cluster 7:
[ 2. 10.  2.  2.  3. 11.  3. 10.  2. 12.]
--------------------
Cluster 8:
[ 3.  7.  2.  8.  2. 11.  3.  6.  3. 12.]
--------------------
Cluster 9:
[3. 7. 2. 7. 3. 4. 2. 8. 2. 3.]
--------------------
Cluster 10:
[ 2.  3.  2. 10.  2. 11.  3.  3.  2.  4.]
--------------------
Cluster 11:
[3. 8. 3. 7. 3. 3. 2. 3. 1. 7.]
--------------------
Cluster 12:
[ 3.  6.  2.  2.  2.  7.  2. 11.  3.  3.]
--------------------
Cluster 13:
[ 3. 10.  3. 11.  2. 11.  3.  7.  2.  7.]
--------------------
Cluster 14:
[ 3. 11.  3. 12.  2.  7.  2. 11.  3.  8.]
----------

In [ ]:
# Mostrar las manos más representativas de cada cluster
for i in range(len(X_representative_digits)):
    print(f"Cluster {i+1}:")
    hand = []
    for j, card_value in enumerate(X_representative_digits[i]):
        card = int(card_value) % 13 + 1  # Valor de la carta
        suit = int(card_value) // 13  # Palo de la carta
        suit_str = ["Hearts", "Diamonds", "Clubs", "Spades"][suit]
        card_str = str(card) if card <= 10 else ["Jack", "Queen", "King", "Ace"][card - 11]
        hand.append(f"{card_str} of {suit_str}")
    print(", ".join(hand))
    print("--------------------")


Cluster 1:
3 of Hearts, 5 of Hearts, 4 of Hearts, 3 of Hearts, 3 of Hearts, 4 of Hearts, 4 of Hearts, 10 of Hearts, 4 of Hearts, Jack of Hearts
--------------------
Cluster 2:
3 of Hearts, Queen of Hearts, 4 of Hearts, King of Hearts, 4 of Hearts, Jack of Hearts, 3 of Hearts, 4 of Hearts, 4 of Hearts, 4 of Hearts
--------------------
Cluster 3:
3 of Hearts, 4 of Hearts, 4 of Hearts, 9 of Hearts, 3 of Hearts, Queen of Hearts, 4 of Hearts, 7 of Hearts, 3 of Hearts, 8 of Hearts
--------------------
Cluster 4:
3 of Hearts, Queen of Hearts, 3 of Hearts, 8 of Hearts, 4 of Hearts, Queen of Hearts, 4 of Hearts, 9 of Hearts, 3 of Hearts, 4 of Hearts
--------------------
Cluster 5:
4 of Hearts, 9 of Hearts, 4 of Hearts, 8 of Hearts, 3 of Hearts, 4 of Hearts, 4 of Hearts, 7 of Hearts, 3 of Hearts, King of Hearts
--------------------
Cluster 6:
3 of Hearts, 4 of Hearts, 4 of Hearts, 8 of Hearts, 4 of Hearts, 5 of Hearts, 4 of Hearts, 7 of Hearts, 4 of Hearts, 9 of Hearts
--------------------
Clust

In [ ]:
y_representative_digits = y_train.values[idxs]
# contiene las respuestas o las y  :V   uqe utiliza idxs  para saber a que cluster pertences

In [ ]:
#creo una regresion logistica

from sklearn.linear_model import LogisticRegression

log_reg2 = LogisticRegression(multi_class="ovr", solver="lbfgs", max_iter=5000, random_state=42)
%time log_reg2.fit(X_representative_digits, y_representative_digits)#tiempo medido
log_reg2.score(X_test, y_test)  #rendimiento

CPU times: user 53.1 ms, sys: 971 µs, total: 54 ms
Wall time: 61 ms


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(


0.3895798293093154

In [ ]:
log_reg = LogisticRegression(multi_class="ovr", solver="lbfgs", max_iter=5000, random_state=42)
%time log_reg.fit(X_train[:3000], y_train[:3000])
log_reg.score(X_test, y_test)

CPU times: user 186 ms, sys: 151 ms, total: 337 ms
Wall time: 181 ms


0.49448786941030937

In [ ]:
#Claro, este código realiza una propagación de etiquetas basada en los clusters encontrados por el algoritmo K-Mean
y_train_propagated = np.empty(len(X_train))
for i in range(k):#se itera sobre los cluster generados
  y_train_propagated[kmeans.labels_==i] = y_representative_digits[i]  #i array boleano que indican qu muestras pertencen al cluster

  log_reg3 = LogisticRegression(multi_class="ovr", solver="lbfgs", max_iter=5000, random_state=42)
%time log_reg3.fit(X_train[:1000], y_train_propagated[:1000])

log_reg3.score(X_test, y_test)#

CPU times: user 92.8 ms, sys: 66.6 ms, total: 159 ms
Wall time: 84.6 ms


0.4501449739125005

zzzzzzzzzzzzzzzz


2 ocpcion
